#!/bin/bash

oc create secret generic sso-config \
  --from-file=secrets/standalone-openshift.xml \
  --from-file=secrets/application-roles.properties \
  --from-file=secrets/application-users.properties \
  --from-file=secrets/logging.properties \
  --from-file=secrets/mgmt-groups.properties \
  --from-file=secrets/mgmt-users.properties \
  -n custom-sso
